# 2. ÇİZİM EKRANI OLUŞTURMA

In [4]:
import cv2
import numpy as np

canvas = np.zeros((512,512,3),dtype = np.uint8) +200
print(canvas)
cv2.imshow("canvas", canvas)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 ...

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]

 [[200 200 200]
  [200 200 200]
  [200 200 200]
  ...
  [200 200 200]
  [200 200 200]
  [200 200 200]]]


canvas = np.zeros()   komutu ekranda siyah bir tuval oluşturur

dtype = np.uint8 uint8 çizim yapmak için lazım olan dtype dır